name: Build
on:
  push:
    branches:
      - master # or the name of your main branch  
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}

          # Optional.
          # github_api_url: https://api.example.com

          # Optional.
          # installation_id: 1337

          # Optional.
          # Using a YAML multiline string to avoid escaping the JSON quotes.
          # permissions: >-
          #   {"members": "read"}

          private_key: ${{ secrets.APP_PRIVATE_KEY }}

          # Optional.
          # repository: owner/repo
      - name: Use token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
      - uses: actions/checkout@v3
        with:
          repository: CovertO/TestInternal
          fetch-depth: 0
          path: test-checkout-internal
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Go mod
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          go env -w GOPRIVATE=github.com/CovertO/TestInternal/
          git config --global url.https://$TOKEN@github.com/.insteadOf https://github.com/
          cat ~/.gitconfig
          go mod vendor