name: Build
on:
  push:
    branches:
      - master # or the name of your main branch  
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate test coverage
        run: |
          make generate-test-coverage
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
